/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package navarro22.calculadora;

/**
 *
 * @author Maria Jose
 */
public class calculador extends javax.swing.JFrame {
    private String digito="";
    double seno=0;
    double coseno=0;
    double loga=0;
    double raizCuadrada=0;
    /**
     * Creates new form calculador
     */
    public calculador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFrame1 = new javax.swing.JFrame();
        labelRaiz = new javax.swing.JLabel();
        labelLog = new javax.swing.JLabel();
        labelSeno = new javax.swing.JLabel();
        labelCoseno = new javax.swing.JLabel();
        labelPantallaRaiz = new javax.swing.JLabel();
        labelResultadoRaiz = new javax.swing.JLabel();
        labelIgualRaiz = new javax.swing.JLabel();
        labelIgualLog = new javax.swing.JLabel();
        labelIgualSeno = new javax.swing.JLabel();
        labelIgualCoseno = new javax.swing.JLabel();
        labelResultadoLog = new javax.swing.JLabel();
        labelResultadoSeno = new javax.swing.JLabel();
        labelPantallaCoseno = new javax.swing.JLabel();
        labelPantallaSeno = new javax.swing.JLabel();
        Boton1 = new javax.swing.JButton();
        Label2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        labelPantallaLog = new javax.swing.JLabel();
        labelResultadoCoseno = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setPreferredSize(new java.awt.Dimension(350, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelRaiz.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelRaiz.setForeground(new java.awt.Color(255, 153, 255));
        labelRaiz.setText("√");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelRaiz, gridBagConstraints);

        labelLog.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelLog.setForeground(new java.awt.Color(255, 153, 255));
        labelLog.setText("log");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelLog, gridBagConstraints);

        labelSeno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelSeno.setForeground(new java.awt.Color(255, 153, 255));
        labelSeno.setText("sen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelSeno, gridBagConstraints);

        labelCoseno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCoseno.setForeground(new java.awt.Color(255, 153, 255));
        labelCoseno.setText("cos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelCoseno, gridBagConstraints);

        labelPantallaRaiz.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPantallaRaiz.setForeground(new java.awt.Color(255, 153, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelPantallaRaiz, gridBagConstraints);

        labelResultadoRaiz.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelResultadoRaiz.setForeground(new java.awt.Color(255, 153, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelResultadoRaiz, gridBagConstraints);

        labelIgualRaiz.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelIgualRaiz.setForeground(new java.awt.Color(255, 153, 255));
        labelIgualRaiz.setText("=");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelIgualRaiz, gridBagConstraints);

        labelIgualLog.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelIgualLog.setForeground(new java.awt.Color(255, 153, 255));
        labelIgualLog.setText("=");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelIgualLog, gridBagConstraints);

        labelIgualSeno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelIgualSeno.setForeground(new java.awt.Color(255, 153, 255));
        labelIgualSeno.setText("=");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelIgualSeno, gridBagConstraints);

        labelIgualCoseno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelIgualCoseno.setForeground(new java.awt.Color(255, 153, 255));
        labelIgualCoseno.setText("=");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelIgualCoseno, gridBagConstraints);

        labelResultadoLog.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelResultadoLog.setForeground(new java.awt.Color(255, 153, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelResultadoLog, gridBagConstraints);

        labelResultadoSeno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelResultadoSeno.setForeground(new java.awt.Color(255, 153, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelResultadoSeno, gridBagConstraints);

        labelPantallaCoseno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPantallaCoseno.setForeground(new java.awt.Color(255, 153, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelPantallaCoseno, gridBagConstraints);

        labelPantallaSeno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPantallaSeno.setForeground(new java.awt.Color(255, 153, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelPantallaSeno, gridBagConstraints);

        Boton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton1.setText("1");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Boton1, gridBagConstraints);

        Label2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label2.setText("2");
        Label2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Label2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Label2, gridBagConstraints);

        Boton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton3.setText("3");
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Boton3, gridBagConstraints);

        Boton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton4.setText("4");
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Boton4, gridBagConstraints);

        Boton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton5.setText("5");
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Boton5, gridBagConstraints);

        Boton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton6.setText("6");
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Boton6, gridBagConstraints);

        Boton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton7.setText("7");
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Boton7, gridBagConstraints);

        Boton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton8.setText("8");
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Boton8, gridBagConstraints);

        Boton9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton9.setText("9");
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Boton9, gridBagConstraints);

        Boton0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Boton0.setText("0");
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(Boton0, gridBagConstraints);

        botonIgual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(botonIgual, gridBagConstraints);

        labelPantallaLog.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPantallaLog.setForeground(new java.awt.Color(255, 153, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelPantallaLog, gridBagConstraints);

        labelResultadoCoseno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelResultadoCoseno.setForeground(new java.awt.Color(255, 153, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(labelResultadoCoseno, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        digito += "1";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Label2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Label2ActionPerformed
        digito += "2";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Label2ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        digito += "4";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        digito += "5";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        digito += "6";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Boton6ActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        digito += "7";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        digito += "8";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        digito += "9";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
        digito += "0";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Boton0ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        digito += "3";
        labelPantallaRaiz.setText(digito);
        labelPantallaSeno.setText(digito);
        labelPantallaLog.setText(digito);
        labelPantallaCoseno.setText(digito);
    }//GEN-LAST:event_Boton3ActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        double sin=Double.parseDouble(digito);
            double cos=Double.parseDouble(digito);
            double log=Double.parseDouble(digito);
            double raiz=Double.parseDouble(digito);
            raizCuadrada=Math.sqrt(raiz);
            seno= Math.sin(sin);
            coseno=Math.cos(cos);
            loga=Math.log(log);
            labelResultadoRaiz.setText(String.format("%.4f",raizCuadrada));
            labelResultadoSeno.setText(String.format("%.4f",seno));
            labelResultadoCoseno.setText(String.format("%.4f",coseno));
            labelResultadoLog.setText(String.format("%.4f",loga));
    }//GEN-LAST:event_botonIgualActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton0;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton Label2;
    private javax.swing.JButton botonIgual;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel labelCoseno;
    private javax.swing.JLabel labelIgualCoseno;
    private javax.swing.JLabel labelIgualLog;
    private javax.swing.JLabel labelIgualRaiz;
    private javax.swing.JLabel labelIgualSeno;
    private javax.swing.JLabel labelLog;
    private javax.swing.JLabel labelPantallaCoseno;
    private javax.swing.JLabel labelPantallaLog;
    private javax.swing.JLabel labelPantallaRaiz;
    private javax.swing.JLabel labelPantallaSeno;
    private javax.swing.JLabel labelRaiz;
    private javax.swing.JLabel labelResultadoCoseno;
    private javax.swing.JLabel labelResultadoLog;
    private javax.swing.JLabel labelResultadoRaiz;
    private javax.swing.JLabel labelResultadoSeno;
    private javax.swing.JLabel labelSeno;
    // End of variables declaration//GEN-END:variables
}
